"""init

Revision ID: a161adc0c92e
Revises: 
Create Date: 2021-09-23 11:33:30.882426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a161adc0c92e'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_value_pair',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_key_value_pair'))
    )
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_chain', sa.Text(), nullable=False),
    sa.Column('to_chain', sa.Text(), nullable=False),
    sa.Column('transaction_id', sa.Text(), nullable=False),
    sa.Column('transaction_id_old', sa.Text(), nullable=False),
    sa.Column('was_processed', sa.Boolean(), nullable=False),
    sa.Column('num_votes', sa.Integer(), nullable=False),
    sa.Column('receiver_address', sa.Text(), nullable=False),
    sa.Column('token_address', sa.Text(), nullable=False),
    sa.Column('token_symbol', sa.Text(), nullable=False),
    sa.Column('amount_wei', sa.Integer(), nullable=False),
    sa.Column('user_data', sa.Text(), nullable=False),
    sa.Column('event_block_number', sa.Integer(), nullable=False),
    sa.Column('event_block_hash', sa.Text(), nullable=False),
    sa.Column('event_transaction_hash', sa.Text(), nullable=False),
    sa.Column('event_log_index', sa.Integer(), nullable=False),
    sa.Column('executed_transaction_hash', sa.Text(), nullable=False),
    sa.Column('executed_block_hash', sa.Text(), nullable=False),
    sa.Column('executed_block_number', sa.Integer(), nullable=False),
    sa.Column('executed_log_index', sa.Integer(), nullable=False),
    sa.Column('has_error_token_receiver_events', sa.Boolean(), nullable=False),
    sa.Column('error_data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer'))
    )
    op.create_index(op.f('ix_transfer_transaction_id'), 'transfer', ['transaction_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_transaction_id'), table_name='transfer')
    op.drop_table('transfer')
    op.drop_table('key_value_pair')
    # ### end Alembic commands ###
